### ISSUE TITLE
Hardcoded absolute path for find causes build failure on NixOS

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/abcBridge#11]
In the `scripts/setup-abc.sh` script, the path to the `find` executable is hardcoded to `/usr/bin/find`. Since NixOS stores executables in `/nix/store/...`, this causes a build failure. Is there a reason that this is hardcoded, rather than determined by the user's `PATH`? I'm happy to send a pull request.

**Comment by atomb** [comment]
The absolute paths are currently there to avoid build failures on Windows (MinGW, specifically). However, `setup-abc.sh` does much less now than it used to, and it may make more sense to fold its functionality into `Setup.hs`, which would generally be more portable (probably across both Nix and Windows).
