### ISSUE TITLE
XCode 12 on macOS Catalina requires C99 for vsnprintf

### ISSUE THREAD

**Issue by lisanna-dettwyler** [GaloisInc/abcBridge#15]
Building abcBridge isn't working on macOS Catalina in newer xcode versions, because of XCode's [stdio.h](https://opensource.apple.com/source/Libc/Libc-1353.41.1/include/stdio.h.auto.html) guarding `vsnprintf` and friends behind `_C99_SOURCE`:

```c
#if __DARWIN_C_LEVEL >= 200112L || defined(_C99_SOURCE) || defined(__cplusplus)
__BEGIN_DECLS
int	 snprintf(char * __restrict __str, size_t __size, const char * __restrict __format, ...) __printflike(3, 4);
int	 vfscanf(FILE * __restrict __stream, const char * __restrict __format, va_list) __scanflike(2, 0);
int	 vscanf(const char * __restrict __format, va_list) __scanflike(1, 0);
int	 vsnprintf(char * __restrict __str, size_t __size, const char * __restrict __format, va_list) __printflike(3, 0);
int	 vsscanf(const char * __restrict __str, const char * __restrict __format, va_list) __scanflike(2, 0);
__END_DECLS
#endif /* __DARWIN_C_LEVEL >= 200112L || defined(_C99_SOURCE) || defined(__cplusplus) */
```

However, `_ANSI_SOURCE` is currently being set on macOS: https://github.com/GaloisInc/abcBridge/blob/cb943e93de0d38bcf59faec0c60739e222fb4adb/abcBridge.cabal#L76-L92

This causes:

```
In file included from cbits/abcBridgeGiaDup.c:1:0: error: 

In file included from abc-build/src/aig/aig/aig.h:34:0: error: 

In file included from abc-build/src/misc/vec/vec.h:33:0: error: 

abc-build/src/misc/vec/vecStr.h:700:14: error:
     error: implicitly declaring library function 'vsnprintf' with type 'int (char *, unsigned long, const char *, struct __va_list_tag *)' [-Werror,-Wimplicit-function-declaration]
        nAdded = vsnprintf( Vec_StrLimit(p), nSize, format, args );
                 ^
    |
700 |     nAdded = vsnprintf( Vec_StrLimit(p), nSize, format, args );
    |              ^

abc-build/src/misc/vec/vecStr.h:700:14: error:
     note: include the header <stdio.h> or explicitly provide a declaration for 'vsnprintf'
    |
700 |     nAdded = vsnprintf( Vec_StrLimit(p), nSize, format, args );
    |              ^
2 warnings and 1 error generated.
`gcc' failed in phase `C Compiler'. (Exit code: 1)
```

**Comment by robdockins** [comment]
Thanks for looking into this!  It isn't a nice fix, but we could try setting `-Wno-error=implicit-function-declaration`, which, I think, would restore the prior behavior (warning, but no error).

**Comment by lisanna-dettwyler** [comment]
An actual fix to this based on some testing I've done could be to just set `_C99_SOURCE` instead of `_ANSI_SOURCE` (thanks @kquick for the suggestion). That resolves this issue at least. I think it should also continue to solve the original `stdint.h` issue seen in older versions of xcode, but I haven't explicitly tried that scenario yet.

**Comment by weaversa** [comment]
I seem to remember that abc targets c89?

**Comment by kquick** [comment]
I didn't see anything in the ABC README that indicated a specific revision of the standard, but vsnprintf was introduced in c99, so it's possible that an original c89 intention has shifted a bit.  If you have a reference for the c89 intention @weaversa we could explore this more.

**Comment by lisanna-dettwyler** [comment]
Based on additional testing and research I've done, I think that the best approach here is to not set any flags here at all, by reverting the original commit (#17). saw-script with abcBridge builds [successfully on macOS 10.15](https://github.com/GaloisInc/saw-script/pull/896/checks?check_run_id=1381821260) with the `_ANSI_SOURCE` flag removed from abcBridge. Also tried building manually against 10.14 and was able to get a successful build, so it looks like this workaround is no longer needed.

**Comment by kquick** [comment]
Not having to have workarounds would be even better. I suppose if someone truly did need this in an older environment that was affected, they could manually re-introduce the workaround.
